### ISSUE TITLE
Products suppliers feature

### ISSUE THREAD

**Issue by EngrTaofeek** [Sidnahar04/travelexpertsphase2#4]
GUI for Products Supplier:
View Products Suppliers Screen: This is the default screen should display all products suppliers in the database and have buttons that do crud(add/edit/delete)
Add/Edit Product Supplier Screen: Basic screen to create and update products suppliers.
Delete Product Supplier Function: Allow users to delete a product with confirmation.
Search/Filter Functionality: Add search functionality for products, enabling filtering based on keywords.
TIP: 
1 TABLES TO BE USED for viewing and Modifying Product: Product Supplier table for viewing and changing
2 TABLES TO BE USED FOR ADDING NEW Product Supplier: Suppliers table

**Comment by Sidnahar04** [comment]
https://github.com/Sidnahar04/travelexpertsphase2/pull/22

Add/Edit of Product and Supplier Done.
