### ISSUE TITLE
Packages feature

### ISSUE THREAD

**Issue by EngrTaofeek** [Sidnahar04/travelexpertsphase2#5]
Display Packages: Display all packages in the database and it should be clickable which would take the user to view/modify that particular package. There should also be add new package and delete package buttons which would do the intended purpose
View/Modify packages: Interface to rename package,assign or remove products and suppliers from packages.
Filter/Search all Packages: Allow users to filter and search products and suppliers linked to a package.
Filter/Search within Package: Allow users to filter and search products and suppliers linked to a package.
TABLES
Packages
Packages product suppliers

FURTHER CONSIDERATIONS
the Package End Date must be later than Package Start Date
Package Name and Package Description cannot be null

**Comment by Sidnahar04** [comment]
CRUD of packages is done.But I haven't added the products and linked them yet.

**Comment by Sidnahar04** [comment]
https://github.com/Sidnahar04/travelexpertsphase2/pull/18

Completed
